version: '3.8'

services:
  api:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: ProjectManagerAPI
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=ProjectManagerAPI
      - JWT_SECRET=sample123
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: DockerDB
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ProjectManagerAPI
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
